import { Product } from '@/types';

export const DUMMY_PRODUCTS: Product[] = [
  // ── ELECTRONICS ──────────────────────────────────────────────
  {
    id: 'prod-1',
    title: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise cancellation with 30-hour battery life. Crystal-clear hands-free calling and Alexa voice control.',
    price: 29990,
    discount_price: 24990,
    category_id: 'electronics',
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 12,
    is_active: true,
    specs: {
      Brand: 'Sony', Model: 'WH-1000XM5', Connectivity: 'Bluetooth 5.2',
      'Battery Life': '30 Hours', 'Noise Cancellation': 'Yes', Color: 'Matte Black',
      Weight: '250g', 'Foldable': 'Yes',
    },
  },
  {
    id: 'prod-2',
    title: 'Apple MacBook Air M3 13-inch',
    description: 'Supercharged by the M3 chip. Up to 18 hours of battery life. 15% faster than the previous generation.',
    price: 114990,
    discount_price: 104990,
    category_id: 'electronics',
    image_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 5,
    is_active: true,
    specs: {
      Brand: 'Apple', Processor: 'Apple M3', RAM: '8GB', Storage: '256GB SSD',
      Display: '13.6 inch Liquid Retina', 'Battery Life': '18 Hours', OS: 'macOS Sonoma',
    },
  },
  {
    id: 'prod-3',
    title: 'Samsung Galaxy S24 Ultra',
    description: 'The ultimate Galaxy AI phone. Titanium frame, 200MP camera, built-in S Pen.',
    price: 134999,
    discount_price: 119999,
    category_id: 'electronics',
    image_url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 8,
    is_active: true,
    specs: {
      Brand: 'Samsung', Display: '6.8 inch Dynamic AMOLED', Processor: 'Snapdragon 8 Gen 3',
      RAM: '12GB', Storage: '256GB', Camera: '200MP + 12MP + 10MP + 50MP', Battery: '5000mAh',
    },
  },
  {
    id: 'prod-4',
    title: 'Sony 4K OLED Smart TV 55"',
    description: 'Perfect blacks, vibrant colors and immersive sound. BRAVIA XR processing with Google TV.',
    price: 149990,
    discount_price: 119990,
    category_id: 'electronics',
    image_url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 3,
    is_active: true,
    specs: {
      Brand: 'Sony', Screen: '55 inch OLED', Resolution: '4K (3840x2160)', OS: 'Google TV',
      HDR: 'Dolby Vision, HDR10', 'Smart Features': 'Voice Remote, Google Assistant',
    },
  },
  {
    id: 'prod-5',
    title: 'Bose QuietComfort Earbuds II',
    description: 'The best noise cancelling earbuds on the market. Personalized, every time.',
    price: 26900,
    discount_price: 19990,
    category_id: 'electronics',
    image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 20,
    is_active: true,
    specs: {
      Brand: 'Bose', Type: 'In-Ear TWS', 'Playtime': '6 Hours (24 with case)',
      Bluetooth: '5.3', 'Noise Cancellation': 'Active', 'Water Resistant': 'IPX4',
    },
  },

  // ── MOBILES & ACCESSORIES ────────────────────────────────────
  {
    id: 'prod-6',
    title: 'boAt Rockerz 450 Wireless Headphone',
    description: '15 hours battery, super bass, and foldable design. Perfect for daily commute.',
    price: 1999,
    discount_price: 999,
    category_id: 'mobiles',
    image_url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 50,
    is_active: true,
    specs: {
      Brand: 'boAt', Connectivity: 'Bluetooth 5.0', 'Battery Life': '15 Hours',
      'Driver Size': '40mm', 'Foldable': 'Yes',
    },
  },
  {
    id: 'prod-7',
    title: 'Anker 65W GaN USB-C Charger',
    description: 'Charge your phone, tablet, and laptop simultaneously with one compact charger.',
    price: 2999,
    discount_price: 1799,
    category_id: 'mobiles',
    image_url: 'https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 100,
    is_active: true,
    specs: {
      Brand: 'Anker', Power: '65W', Ports: '3 (USB-C x2 + USB-A)',
      Technology: 'GaN II', Compatibility: 'Universal',
    },
  },
  {
    id: 'prod-8',
    title: 'Spigen MagFit Phone Case for iPhone 15 Pro',
    description: 'Slim armor with MagSafe compatibility. Military-grade drop protection.',
    price: 1599,
    discount_price: 1199,
    category_id: 'mobiles',
    image_url: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 200,
    is_active: true,
    specs: {
      Brand: 'Spigen', Compatibility: 'iPhone 15 Pro', Material: 'TPU + Polycarbonate',
      MagSafe: 'Yes', 'Drop Protection': 'Military Grade (MIL-STD-810G)',
    },
  },
  {
    id: 'prod-9',
    title: 'Portronics ManyFix Qi Wireless Charger',
    description: '15W fast wireless charging pad compatible with all Qi devices.',
    price: 999,
    discount_price: 699,
    category_id: 'mobiles',
    image_url: 'https://images.unsplash.com/photo-1596455607563-ad6193f76b17?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 75,
    is_active: true,
    specs: {
      Brand: 'Portronics', Power: '15W', Standard: 'Qi', Compatible: 'iPhone 15, Samsung Galaxy, etc.',
    },
  },
  {
    id: 'prod-10',
    title: 'JBL Clip 4 Portable Bluetooth Speaker',
    description: 'Ultra-portable clip-on speaker with IP67 waterproof rating and 10-hour playtime.',
    price: 3499,
    discount_price: 2499,
    category_id: 'mobiles',
    image_url: 'https://images.unsplash.com/photo-1608223654407-28d116279f53?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 30,
    is_active: true,
    specs: {
      Brand: 'JBL', 'Playtime': '10 Hours', Waterproof: 'IP67', Bluetooth: '5.1',
      'Clip Feature': 'Yes',
    },
  },

  // ── HOME DECOR ───────────────────────────────────────────────
  {
    id: 'prod-11',
    title: 'Philips Hue Smart LED Bulb (Pack of 3)',
    description: '16 million colors. Control with your phone or voice. Works with Alexa & Google.',
    price: 3499,
    discount_price: 2799,
    category_id: 'decor',
    image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 40,
    is_active: true,
    specs: {
      Brand: 'Philips Hue', Wattage: '9W (60W equiv.)', Colors: '16 Million',
      Protocol: 'Zigbee', 'Works With': 'Alexa, Google Home, Apple HomeKit',
    },
  },
  {
    id: 'prod-12',
    title: 'Minimalist Geometric Wall Art Set',
    description: 'Set of 3 framed canvas prints. Modern geometric design for living rooms & bedrooms.',
    price: 2499,
    discount_price: 1499,
    category_id: 'decor',
    image_url: 'https://images.unsplash.com/photo-1567225557594-88d73e55f2cb?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 15,
    is_active: true,
    specs: {
      Material: 'Canvas + MDF Frame', 'Set Size': '3 Pieces', Size: '12"x12" each',
      Style: 'Modern Geometric', 'Ready to Hang': 'Yes',
    },
  },
  {
    id: 'prod-13',
    title: 'Wooden Floating Wall Shelves (Set of 3)',
    description: 'Rustic wooden wall shelves for books, plants, and decor. Easy to install.',
    price: 1799,
    discount_price: 1299,
    category_id: 'decor',
    image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 22,
    is_active: true,
    specs: {
      Material: 'Sheesham Wood', Dimensions: '24"x6" per shelf', Color: 'Natural Brown',
      'Load Capacity': '10kg per shelf', 'Hardware Included': 'Yes',
    },
  },
  {
    id: 'prod-14',
    title: 'Ceramic Matte Flower Vase Set',
    description: 'Modern nordic-style ceramic vases in 3 sizes. Perfect for dried or fresh flowers.',
    price: 899,
    discount_price: 649,
    category_id: 'decor',
    image_url: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 60,
    is_active: true,
    specs: {
      Material: 'Ceramic', 'Set of': '3 Pieces', Style: 'Nordic Minimalist',
      Colors: 'White, Beige, Terracotta', Waterproof: 'Yes',
    },
  },
  {
    id: 'prod-15',
    title: 'Luxury Reed Diffuser - Lavender',
    description: 'Fills your room with a calming lavender scent for up to 3 months.',
    price: 799,
    discount_price: 549,
    category_id: 'decor',
    image_url: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 80,
    is_active: true,
    specs: {
      Fragrance: 'Lavender', Volume: '150ml', 'Duration': '3 Months', Sticks: '8 Rattan Reed Sticks',
    },
  },

  // ── HOME UTILITY ─────────────────────────────────────────────
  {
    id: 'prod-16',
    title: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker',
    description: 'Replaces 7 kitchen appliances. Cook up to 70% faster. 6-litre capacity.',
    price: 14999,
    discount_price: 9999,
    category_id: 'utility',
    image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 7,
    is_active: true,
    specs: {
      Brand: 'Instant Pot', Capacity: '6 Litres', Functions: '7-in-1',
      Wattage: '1000W', Material: 'Stainless Steel Inner Pot',
    },
  },
  {
    id: 'prod-17',
    title: 'Dyson V12 Detect Slim Cordless Vacuum',
    description: 'Laser reveals microscopic dust. Up to 60 minutes of run time.',
    price: 54990,
    discount_price: 44990,
    category_id: 'utility',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 4,
    is_active: true,
    specs: {
      Brand: 'Dyson', 'Battery Life': '60 Minutes', 'Suction': '150 AW',
      Filter: 'HEPA', Weight: '2.2kg',
    },
  },
  {
    id: 'prod-18',
    title: 'Milton Thermosteel Flask 1 Litre',
    description: 'Keeps beverages hot for 24 hours and cold for 48 hours.',
    price: 899,
    discount_price: 649,
    category_id: 'utility',
    image_url: 'https://images.unsplash.com/photo-1553104216-9d6e7e8a9f93?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 150,
    is_active: true,
    specs: {
      Brand: 'Milton', Capacity: '1 Litre', Material: 'Stainless Steel',
      'Hot Duration': '24 Hours', 'Cold Duration': '48 Hours', BPA: 'BPA Free',
    },
  },
  {
    id: 'prod-19',
    title: 'Pigeon Healthifry Digital Air Fryer',
    description: '1200W digital air fryer. Cook 360° with 80% less oil. 4.2 litre capacity.',
    price: 3999,
    discount_price: 2799,
    category_id: 'utility',
    image_url: 'https://images.unsplash.com/photo-1626509653291-18d9a934b9db?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 18,
    is_active: true,
    specs: {
      Brand: 'Pigeon', Capacity: '4.2 Litres', Wattage: '1200W',
      'Temperature Range': '80°C - 200°C', Digital: 'Yes',
    },
  },
  {
    id: 'prod-20',
    title: 'Lifetime Smart Lock Padlock',
    description: 'Fingerprint + PIN + Key unlocking. Works offline. Weatherproof design.',
    price: 2499,
    discount_price: 1799,
    category_id: 'utility',
    image_url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 25,
    is_active: true,
    specs: {
      Brand: 'Lifetime', 'Unlock Methods': 'Fingerprint + PIN + Key',
      Waterproof: 'IP65', Material: 'Zinc Alloy', 'Battery': 'Rechargeable USB-C',
    },
  },
];
